import type { PaintColor } from './types';

export const COLORS: PaintColor[] = [
  // Whites & Off-Whites
  { name: 'Alabaster', hex: '#f2e9dc' },
  { name: 'Pure White', hex: '#f5f5f5' },
  { name: 'Snowbound', hex: '#fbf9f3' },
  { name: 'Chantilly Lace', hex: '#f0f2eb' },
  { name: 'White Dove', hex: '#f0efe9' },
  { name: 'Cloud White', hex: '#f3f2e9' },
  { name: 'Swiss Coffee', hex: '#ddd9cd' },
  { name: 'Shoji White', hex: '#e9e2d7' },

  // Grays
  { name: 'Agreeable Gray', hex: '#d1c7b8' },
  { name: 'Repose Gray', hex: '#c0b9ae' },
  { name: 'Mindful Gray', hex: '#b3ada4' },
  { name: 'Dovetail', hex: '#8f8880' },
  { name: 'Gauntlet Gray', hex: '#807b75' },
  { name: 'Iron Ore', hex: '#4f4e4c' },
  { name: 'Peppercorn', hex: '#585652' },
  { name: 'Tricorn Black', hex: '#2f2f2f' },
  { name: 'Light French Gray', hex: '#c8c5c0' },
  { name: 'Stonington Gray', hex: '#cac8c2' },
  { name: 'Coventry Gray', hex: '#9da0a5' },
  { name: 'Chelsea Gray', hex: '#898987' },
  { name: 'Kendall Charcoal', hex: '#696865' },
  { name: 'Amherst Gray', hex: '#777873' },

  // Beiges & Tans
  { name: 'Accessible Beige', hex: '#d0c4b3' },
  { name: 'Kilim Beige', hex: '#d8c5ac' },
  { name: 'Manchester Tan', hex: '#d2c7b1' },
  { name: 'Balanced Beige', hex: '#c3b8a8' },
  { name: 'Urbane Bronze', hex: '#635f59' },
  { name: 'Natural Linen', hex: '#dcd1c1' },
  { name: 'Grant Beige', hex: '#c1b8a4' },
  { name: 'Pashmina', hex: '#aea899' },
  { name: 'Stone Hearth', hex: '#b3a99a' },

  // Greens
  { name: 'Sea Salt', hex: '#d5dbd5' },
  { name: 'Evergreen Fog', hex: '#6f7469' },
  { name: 'Dried Thyme', hex: '#878370' },
  { name: 'Rosemary', hex: '#77786a' },
  { name: 'Retreat', hex: '#6f6d5e' },
  { name: 'Comfort Gray', hex: '#cdd0c9' },
  { name: 'October Mist', hex: '#a5ac9f' },
  { name: 'Saybrook Sage', hex: '#b7b9a5' },
  { name: 'Caldwell Green', hex: '#717868' },
  { name: 'Hunter Green', hex: '#475347' },
  { name: 'Pewter Green', hex: '#7a7d71' },
  { name: 'Clary Sage', hex: '#c4c4af' },
  { name: 'Liveable Green', hex: '#d5d3c3' },
  { name: 'Rainwashed', hex: '#dbe0d9' },

  // Blues
  { name: 'Naval', hex: '#343c48' },
  { name: 'Aleutian', hex: '#8793a0' },
  { name: 'Hale Navy', hex: '#4f5863' },
  { name: 'Boothbay Gray', hex: '#a9b1b6' },
  { name: 'Van Courtland Blue', hex: '#8ca1a9' },
  { name: 'In The Moment', hex: '#7d8a8b' },
  { name: 'Smoky Blue', hex: '#83919b' },
  { name: 'Upward', hex: '#cdd3d9' },
  { name: 'Krypton', hex: '#d2d9de' },
  { name: 'Tradewind', hex: '#c4d0d2' },
  { name: 'Reflecting Pool', hex: '#b7c7c8' },
  { name: 'Solitude', hex: '#e2e7e9' },
  { name: 'Gentleman\'s Gray', hex: '#3c4b57' },
  { name: 'Web Gray', hex: '#81858a' },

  // Pinks & Reds
  { name: 'Dusty Heather', hex: '#ab9b9f' },
  { name: 'First Light', hex: '#e7d8d6' },
  { name: 'Faint Coral', hex: '#f0dcd3' },
  { name: 'Rosy Peach', hex: '#f5c9b7' },
  { name: 'Malted', hex: '#bcaea9' },
  { name: 'Calamine', hex: '#e4d3d1' },
  { name: 'Setting Plaster', hex: '#e6cdc4' },
  { name: 'Redend Point', hex: '#c8a99a' },
  { name: 'Canyon Clay', hex: '#bb9381' },

  // Yellows & Oranges
  { name: 'Gossamer Veil', hex: '#d9d6ce' },
  { name: 'Navajo White', hex: '#f8e9d2' },
  { name: 'Hawthorne Yellow', hex: '#e8d5a2' },
  { name: 'Weston Flax', hex: '#e8d9b1' },
  { name: 'Pale Moon', hex: '#f7f0d2' },
  { name: 'Golden Straw', hex: '#e9cb96' },
  { name: 'Cavern Clay', hex: '#b58368' },
  { name: 'Studio Clay', hex: '#c7a68a' },

  // Purples
  { name: 'Mauve Finery', hex: '#c4b5ba' },
  { name: 'Veiled Violet', hex: '#d9d5de' },
  { name: 'Hint of Violet', hex: '#e7e3ed' },
  { name: 'Moody Mauve', hex: '#b6a1a7' },
  { name: 'Creative Kisses', hex: '#c3b6c1' },
  
  // Additional Neutrals
  { name: 'Anew Gray', hex: '#c7beaf' },
  { name: 'Mega Greige', hex: '#b3a697' },
  { name: 'Worldly Gray', hex: '#c7bfb3' },
  { name: 'Colonnade Gray', hex: '#c9c2b8' },
  { name: 'On the Rocks', hex: '#dad6ce' },
  { name: 'Crushed Ice', hex: '#d9d8d3' },
  { name: 'Big Chill', hex: '#d7d9d7' },
  { name: 'Silverplate', hex: '#cacaca' },
  { name: 'Dorian Gray', hex: '#a9a69e' },
  { name: 'Acier', hex: '#918f8a' },
  { name: 'Grizzle Gray', hex: '#71706b' },
  { name: 'Black Fox', hex: '#484440' },
  
  // More Beiges
  { name: 'China Doll', hex: '#ede3d3' },
  { name: 'Softer Tan', hex: '#dccbb4' },
  { name: 'Totally Tan', hex: '#d5bca1' },
  { name: 'Basket Beige', hex: '#c6b19a' },
  { name: 'Bungalow Beige', hex: '#c2ae98' },
  { name: 'Macadamia', hex: '#d0ba9f' },
  { name: 'Sandbar', hex: '#d5c2a9' },
  { name: 'Latte', hex: '#c7af96' },
  { name: 'Hopsack', hex: '#bfa98e' },
  { name: 'Favorite Tan', hex: '#c7ae93' },
  
  // More Greens
  { name: 'Filmy Green', hex: '#dde0d5' },
  { name: 'Softened Green', hex: '#d0d1c8' },
  { name: 'Contented', hex: '#b8baa9' },
  { name: 'Svelte Sage', hex: '#b3b09f' },
  { name: 'Coastal Plain', hex: '#a6a38f' },
  { name: 'Riverway', hex: '#50676b' },
  { name: 'Underseas', hex: '#507575' },
  { name: 'Jasper', hex: '#586256' },
  { name: 'Secret Garden', hex: '#636959' },
  { name: 'Rock Garden', hex: '#87897c' },
  { name: 'Ancient Marble', hex: '#e6e4d9' },
  { name: 'Halcyon Green', hex: '#b2c0ba' },
  { name: 'Quietude', hex: '#a0afac' },
  
  // More Blues
  { name: 'Misty', hex: '#cdd3d6' },
  { name: 'Languid Blue', hex: '#d1d8da' },
  { name: 'Niebla Azul', hex: '#b3c1c8' },
  { name: 'Distance', hex: '#8ca0ac' },
  { name: 'Denim', hex: '#6c8398' },
  { name: 'Salty Dog', hex: '#44576a' },
  { name: 'Inky Blue', hex: '#3b4b5b' },
  { name: 'Outerspace', hex: '#4e555b' },
  { name: 'Grays Harbor', hex: '#6d7579' },
  { name: 'Serious Gray', hex: '#9ea4a9' },
  { name: 'Morning Fog', hex: '#c6cbd0' },
  { name: 'North Star', hex: '#d4d9dc' },
  { name: 'Olympus White', hex: '#e2e5e6' },
  
  // Bolds & Brights
  { name: 'Honest Blue', hex: '#7fb5d6' },
  { name: 'Exuberant Pink', hex: '#e8638b' },
  { name: 'Charisma', hex: '#f09c67' },
  { name: 'Positive Red', hex: '#c84037' },
  { name: 'Dynamic Blue', hex: '#2678aa' },
  { name: 'Lakeshore', hex: '#1d8a9f' },
  { name: 'Forward Fuchsia', hex: '#b44a8e' },
  { name: ' चटनी हरा', hex: '#899952' }, // "Chutney Green"
  { name: 'Festoon Aqua', hex: '#9bd1d3' },
  { name: 'Begonia', hex: '#fa7a76' },
  
  // Deep & Moody
  { name: 'Dark Night', hex: '#37414a' },
  { name: 'Cascades', hex: '#48504a' },
  { name: 'Rookwood Dark Red', hex: '#713e3d' },
  { name: 'Carnelian', hex: '#964b43' },
  { name: 'Night Owl', hex: '#514f49' },
  { name: 'Cyberspace', hex: '#434a50' },
  { name: 'Sea Serpent', hex: '#485c5f' },
  { name: 'Porpoise', hex: '#686b6a' },
  { name: 'Roycroft Pewter', hex: '#6f6c65' },
  { name: 'Plum Brown', hex: '#6a514d' },
  { name: 'Vintage Vessel', hex: '#7b5b4f' },
  
  // Pastels
  { name: 'Window Pane', hex: '#e3e8e2' },
  { name: 'Waterscape', hex: '#cddbda' },
  { name: 'Topsail', hex: '#dfe5e5' },
  { name: 'Mint Condition', hex: '#dcf0e7' },
  { name: 'Blushing', hex: '#f6e4e0' },
  { name: 'Romance', hex: '#f3e8e6' },
  { name: 'Peaceful Peach', hex: '#f8e4d8' },
  { name: 'Daffodil', hex: '#fef1c4' },
  { name: 'Glimmer', hex: '#dce5ea' },
  { name: 'Silver Peony', hex: '#e2d5d8' },
  { name: 'Icy Lemonade', hex: '#f7f3d8' },
  
  // More unique colors
  { name: 'Foxhall Green', hex: '#686a5f' },
  { name: 'Dard Hunter Green', hex: '#4c554a' },
  { name: 'Alexandrite', hex: '#88a096' },
  { name: 'Rushing River', hex: '#7b847c' },
  { name: 'Silvermist', hex: '#c7cec8' },
  { name: 'Temperate Taupe', hex: '#beb6a8' },
  { name: 'Fawn Brindle', hex: '#a69a8c' },
  { name: 'Warm Stone', hex: '#a79d92' },
  { name: 'Taupe Tone', hex: '#a09489' },
  { name: 'Intellectual Gray', hex: '#c0b9b0' },
  { name: 'Eider White', hex: '#e6e2db' },
  { name: 'Moderne White', hex: '#e7e3d9' },
  { name: 'Origami White', hex: '#efebe0' },
  { name: 'Westhighland White', hex: '#f6f2e8' },
  { name: 'Creamy', hex: '#f5ead2' },
  { name: 'Casa Blanca', hex: '#f3e5ca' },
  { name: 'Antique White', hex: '#f7ecd9' },
  { name: 'Believable Buff', hex: '#e7d2b9' },
  { name: ' Ivoire', hex: '#f3e0c3' },
  { name: 'Restrained Gold', hex: '#d3b78b' },
  { name: 'Mannered Gold', hex: '#d9b984' },
  { name: 'Brandywine', hex: '#886766' },
  { name: 'Polished Mahogany', hex: '#623f3d' },
  { name: 'Rustic Red', hex: '#a65247' },
  { name: 'Bolero', hex: '#955a50' },
  { name: 'Fireweed', hex: '#a56a5c' },
  { name: 'Pressed Flower', hex: '#cbaea9' },
  { name: 'Wisteria', hex: '#c9c4d9' },
  { name: 'Enchant', hex: '#d5cbe0' },
  { name: 'Quixotic Plum', hex: '#705b67' },
  { name: 'Exclusive Plum', hex: '#65575e' },
  { name: 'Borscht', hex: '#944c5c' },
];